#!/usr/bin/env bash
# For every binary-shipping Rust submodule, pin that Cargo.lock is
# committed at the canonical location (top-level OR src-tauri/ for
# Tauri apps).
#
# `cargo build --locked` is the standard release pattern across all
# release.yml workflows in this org. Without a committed Cargo.lock,
# --locked fails immediately and the release job can't even start.
# Even worse: without --locked, a release could silently roll forward
# a transitive dep between tag-cut and rebuild — unreproducible builds.
#
# Catches: a developer adds a new binary crate to the org and forgets
# to commit Cargo.lock, or .gitignore is configured wrong and ignores
# Cargo.lock. Both have happened in other Rust orgs.
#
# Library-only crates traditionally don't commit Cargo.lock (Cargo
# docs recommend lock files only for binaries). We detect binary
# eligibility by the presence of [[bin]] sections, `default-run`, or
# the canonical src/main.rs / src/bin/ entry-point convention.
set -uo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$root" || exit
ok=1

paths=()
while IFS= read -r line; do
    paths+=("${line#$'\tpath = '}")
done < <(grep $'^\tpath = ' .gitmodules)

# Detect submodules-initialized state
init_count=0
for p in "${paths[@]}"; do
    [[ -d "$p" && -n "$(ls -A "$p" 2>/dev/null)" ]] && init_count=$((init_count + 1))
done
if [[ $init_count -eq 0 ]]; then
    echo "SKIP  no submodules initialized"
    exit 0
fi

is_binary_crate() {
    # Returns 0 if the Cargo.toml or its tree ships at least one binary.
    local cargo="$1"
    local dir="$(dirname "$cargo")"
    # Explicit [[bin]] section.
    if grep -qE '^\[\[bin\]\]' "$cargo" 2>/dev/null; then
        return 0
    fi
    # default-run = "X" implies at least one binary (the one being defaulted).
    if grep -qE '^default-run[[:space:]]*=' "$cargo" 2>/dev/null; then
        return 0
    fi
    # Implicit binary via src/main.rs.
    if [[ -f "$dir/src/main.rs" ]]; then
        return 0
    fi
    # Implicit binaries via src/bin/*.rs.
    if compgen -G "$dir/src/bin/*.rs" >/dev/null 2>&1; then
        return 0
    fi
    return 1
}

binary_repos=0
missing_lock=0
library_repos=0
no_cargo=0

for p in "${paths[@]}"; do
    [[ -d "$p" && -n "$(ls -A "$p" 2>/dev/null)" ]] || continue

    # Locate Cargo.toml and its corresponding lock-file location.
    # For Cargo workspaces, the lock-file is at the workspace ROOT
    # regardless of where each member's Cargo.toml lives. So:
    #   - If top-level Cargo.toml exists AND has [workspace], the lock
    #     goes at top-level (even if the binary lives in a workspace
    #     member like src-tauri/).
    #   - If only src-tauri/Cargo.toml is present (no top-level), the
    #     lock goes in src-tauri/.
    cargo=""
    cargo_dir=""
    if [[ -f "$p/Cargo.toml" ]]; then
        cargo="$p/Cargo.toml"
        cargo_dir="$p"
    elif [[ -f "$p/src-tauri/Cargo.toml" ]]; then
        cargo="$p/src-tauri/Cargo.toml"
        cargo_dir="$p/src-tauri"
    fi

    if [[ -z "$cargo" ]]; then
        no_cargo=$((no_cargo + 1))
        continue
    fi

    # For workspace-only Cargo.toml, fold the binary-eligibility check
    # into the workspace members so a Tauri app with binary under
    # src-tauri/ is still recognized as a binary repo.
    is_bin=0
    if is_binary_crate "$cargo"; then
        is_bin=1
    elif [[ -f "$p/src-tauri/Cargo.toml" ]] && is_binary_crate "$p/src-tauri/Cargo.toml"; then
        is_bin=1
    fi

    if [[ $is_bin -eq 0 ]]; then
        library_repos=$((library_repos + 1))
        echo "INFO  $p: library-only crate, Cargo.lock is optional"
        continue
    fi

    binary_repos=$((binary_repos + 1))
    lock="$cargo_dir/Cargo.lock"
    if [[ ! -f "$lock" ]]; then
        echo "FAIL  $p: binary crate but $lock missing — \`cargo build --locked\` will fail"
        missing_lock=$((missing_lock + 1))
        ok=0
        continue
    fi
    if [[ ! -s "$lock" ]]; then
        echo "FAIL  $p: $lock exists but is empty"
        missing_lock=$((missing_lock + 1))
        ok=0
        continue
    fi
    # Sanity: a real Cargo.lock starts with `# This file is automatically generated`
    if ! head -3 "$lock" | grep -qE 'automatically generated|^version[[:space:]]*=' 2>/dev/null; then
        echo "WARN  $p: $lock present but missing the canonical Cargo header"
    fi
    echo "PASS  $p: $lock present and non-empty"
done

echo "---"
echo "Summary: $binary_repos binary repos checked, $library_repos library-only, $no_cargo non-Rust, $missing_lock missing Cargo.lock"

[[ $ok -eq 1 ]] && exit 0 || exit 1
