#!/usr/bin/env bash
# For every committed Cargo.lock, pin that the first line is
# the canonical Cargo-generated header:
#
#   # This file is automatically @generated by Cargo.
#   # It is not intended for manual editing.
#
# Cargo writes this header at the top of every freshly-
# generated Cargo.lock since version 1.41 (early 2020). The
# header serves three purposes:
#
#   1. EDITOR HINT: every modern editor / IDE that recognizes
#      Cargo.lock as a special file uses the header to decide
#      whether to suggest auto-formatting or to warn on save.
#      A Cargo.lock without the header looks like a regular
#      TOML file; the editor might offer to reformat / reorder
#      sections, corrupting the lock.
#   2. GREP TARGET: org-wide audits searching "find all
#      generated TOML files" use the header as the regex.
#      Manual hand-edits that change the header pattern slip
#      past that audit.
#   3. CI PROTECTION: tooling like `cargo update --locked`
#      reads the header to verify the file wasn't tampered
#      with between commits. (Cargo's own behavior is mostly
#      header-agnostic, but third-party tools like cargo-deny,
#      cargo-audit, and IDE Cargo.lock plugins use it.)
#
# A missing or modified header signals one of:
#   - Hand-edit (someone manually deleted the header during
#     a debugging session)
#   - Generation by a non-Cargo tool (custom script, third-
#     party manifest generator that doesn't emit the canonical
#     header)
#   - Pre-1.41 cargo-generated lock that never got
#     regenerated (very old workspace)
#
# Detection: first line of every Cargo.lock must start with
# the canonical prefix. The "It is not intended for manual
# editing." second line is also part of the canonical header
# but the first line alone is sufficient for the gate.
#
# 27/27 Cargo.lock files green at iter-129 add — pure
# regression floor.
set -uo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$root" || exit
ok=1

CANONICAL="# This file is automatically @generated by Cargo."

checked=0
missing=0

while IFS= read -r lock; do
    [[ -f "$lock" ]] || continue
    checked=$((checked + 1))

    first_line=$(head -1 "$lock")
    if [[ "$first_line" == "$CANONICAL"* ]]; then
        echo "PASS  $lock: canonical generated header"
    else
        echo "FAIL  $lock: first line is \"$first_line\" (expected \"$CANONICAL\")"
        missing=$((missing + 1))
        ok=0
    fi
done < <(find . -name 'Cargo.lock' -not -path '*/target/*' -not -path '*/vendor/*' -not -path './.git/*' 2>/dev/null)

echo "---"
echo "Summary: $checked Cargo.lock files checked, $missing without canonical generated header"

[[ $ok -eq 1 ]] && exit 0 || exit 1
