#!/usr/bin/env bash
set -euo pipefail

# collect-pdfs.sh — centralize every authored PDF across the whole MenkeTechnologies
# monorepo into ONE folder with a manifest, so the full catalog is trackable in one place.
#
# It gathers two families and copies them, with canonical names, into:
#     MenkeTechnologiesPublications/all-pdfs/
# and writes MANIFEST.md (page counts + category + source path + grand total).
#
# Families:
#   1. Publications books + reference manuals — MenkeTechnologiesPublications/<product>/docs/{book,reference}.pdf
#   2. Audio-plugin + UI manuals — app-store/docs/*.pdf (the published store mirror),
#      plus the zpwr-clip-engine reference (only built inside the vendored copy).
#
# Deliberately EXCLUDED as third-party / vendored duplicates:
#   */build/*  */_deps/*  */node_modules/*  */vendor/*  */libs/*   (JUCE, CLAP, VST3 SDK,
#   the nested patch-core/clip-engine/ztranslator copies), and the app-store zemacs-reference
#   mirror (identical to Publications/zemacs — counted once, under Publications).
#
# Re-run any time (idempotent): it wipes and rebuilds all-pdfs/ from current sources, so a
# newly-written or rebuilt book shows up automatically. Requires: bash, mdls (macOS).

ROOT=$(cd "$(dirname "$0")/.." && pwd)
OUT="$ROOT/MenkeTechnologiesPublications/all-pdfs"
MANIFEST="$OUT/MANIFEST.md"

pages() { # robust against a freshly-copied file Spotlight hasn't indexed yet
  local n
  n=$(mdls -name kMDItemNumberOfPages -raw "$1" 2>/dev/null | grep -Eo '^[0-9]+' || true)
  if [[ -z $n ]]; then mdimport "$1" 2>/dev/null || true
        n=$(mdls -name kMDItemNumberOfPages -raw "$1" 2>/dev/null | grep -Eo '^[0-9]+' || true); fi
  echo "${n:-0}"
}

# category by product name — coarse buckets for the manifest
category_for() {
  case "$1" in
    strykelang|zshrs|elisprs|awkrs|vimlrs|zemacs) echo "Language reference" ;;
    fusevm|zterminal|powerliners|desktop-in-rust|inventions|ztmux|zwire) echo "Companion" ;;
    zpwr) echo "Encyclopedia" ;;
    fantasy|scifi|scifi2|scifi3) echo "Novel" ;;
    zpwr-synth|zpwr-fx|zpwr-midi-fx|zpwr-daw|zpwr-patch-core|zpwr-clip-engine) echo "Audio / DSP" ;;
    zgui-core) echo "UI catalog" ;;
    *) echo "Other" ;;
  esac
}

rm -rf "$OUT"; mkdir -p "$OUT"

# the 34 PDF copies are a regenerable local browse-folder — they already live (tracked)
# in their home repos, so don't double-store the binaries in git. Only MANIFEST.md is tracked.
cat > "$OUT/.gitignore" <<'GI'
# regenerable copies — rebuild with scripts/collect-pdfs.sh
*.pdf
GI

# rows collected as: pages<TAB>category<TAB>destname<TAB>source-relpath
rows=()
copy() { # src  destname  product
  local src=$1 dest=$2 prod=$3
  [[ -f $src ]] || { echo "  ! missing: $src" >&2; return 0; }
  cp -f "$src" "$OUT/$dest"
  rows+=("$(pages "$src")	$(category_for "$prod")	$dest	${src#$ROOT/}")
}

echo "collecting Publications books + references…"
for d in "$ROOT"/MenkeTechnologiesPublications/*/; do
  prod=$(basename "$d")
  [[ $prod == all-pdfs || $prod == docs || $prod == src || $prod == tests ]] && continue
  d=${d%/}
  [[ -f "$d/docs/book.pdf"      ]] && copy "$d/docs/book.pdf"      "$prod-book.pdf"      "$prod"
  [[ -f "$d/docs/reference.pdf" ]] && copy "$d/docs/reference.pdf" "$prod-reference.pdf" "$prod"
done

echo "collecting audio-plugin + UI manuals (app-store mirror)…"
for f in "$ROOT"/app-store/docs/*.pdf; do
  [[ -f $f ]] || continue
  base=$(basename "$f")
  # skip the zemacs store mirror — same doc as Publications/zemacs-reference
  [[ $base == zemacs-reference.pdf ]] && continue
  prod=${base%-reference.pdf}; prod=${prod%-block-catalog.pdf}; prod=${prod%-component-catalog.pdf}
  copy "$f" "$base" "$prod"
done

# ---- write MANIFEST.md ----
total_pages=0; count=0
for r in "${rows[@]}"; do total_pages=$(( total_pages + ${r%%$'\t'*} )); count=$(( count + 1 )); done

{
  echo "# MenkeTechnologies — Central PDF Catalog"
  echo
  echo "Every authored PDF across the stack, gathered here by \`scripts/collect-pdfs.sh\`."
  echo "Re-run that script to rebuild this folder from current sources."
  echo
  echo "**$count PDFs · $total_pages pages.**"
  echo
  echo "| # | Document | Category | Pages | Source |"
  echo "|--:|----------|----------|------:|--------|"
  i=0
  printf '%s\n' "${rows[@]}" | sort -t$'\t' -k2,2 -k3,3 | while IFS=$'\t' read -r pg cat dest src; do
    i=$((i+1)); echo "| $i | \`$dest\` | $cat | $pg | \`$src\` |"
  done
  echo
  echo "_Generated by \`scripts/collect-pdfs.sh\`; do not edit by hand._"
} > "$MANIFEST"

echo
echo "wrote $count PDFs ($total_pages pages) → ${OUT#$ROOT/}/"
echo "manifest → ${MANIFEST#$ROOT/}"
